version: "3.9"


services:
  db:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: broken_toy_shop
      POSTGRES_USER: broken_toy_shop
      POSTGRES_PASSWORD: broken_toy_shop
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data:rw
    command: ["postgres", "-c", "log_statement=all", "-c", "log_duration=on"]

volumes:
  db: {}
